name: angular_dart_demo
version: 1.0.0
dependencies:
  angular: ">=1.0.0 <2.0.0"
  browser: ">=0.10.0+2 <0.11.0"
  web_components: ">=0.9.0 <0.10.0"
  js: any
  firebase: ">=0.1.1+3 <0.2.0"
#  angularfire:
#    git:
#      url: https://github.com/mhevery/angularFire
#      ref: dart

dev_dependencies:
  unittest: any
